---
title: Disekitar Game
timezone: Asia/Makassar
collections:
  posts:
    title: Posts
    output: true
    Author:
    - sal
    - john
  stories:
    title: Stories
    output: true
  uploads:
    title: Uploads
    output: true
name: Disekitar Game
description: Disekitar Game adalah media informasi digital yang menyajikan edukasi,
  berita, rumor, tips & trik, serta berbagai topik menarik seputar game. Kami berusaha
  memberikan pandangan terbaik serta konten yang menarik dan informatif untuk menambah
  wawasan pemirsa mengenai dunia teknologi khususnya pada industri game.
logo: assets/images/logo-1-min.gif
favicon: assets/images/dsg-logo-icon-1.png
url: https://disekitargame.com
baseurl: ''
google_analytics: G-3ZND91CGZD
disqus: disekitar-game
mailchimp-list: https://space.us3.list-manage.com/subscribe?u=119b8c921721eaa747d4230ea&id=d8f6b5e860
include:
- _pages
- _redirects
permalink: "/:title/"
email: support@disekitargame.com
authors:
  sal:
    name: arya
    display_name: Arya P.
    gravatar: 01bcc0368a8e3c305e2b497d369fbee2
    email: kadekarya4@gmail.com
    web: https://disekitargame.com/authors/arya/
    twitter: 
    description: Founder
  john:
    name: angga
    display_name: Dimaru Permana
    gravatar: db72fc2b17acc4c0cdba7bff28eb30c8
    email: 
    web: https://disekitargame.com/authors/angga/
    twitter: 
    description: Founder
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
- jekyll-figure
jekyll-archives:
  enabled: 
  layout: archive
  permalinks:
    category: "/category/:name/"
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 15
  permalink: "/page/:num/"
  title: ":title"
  limit: 0
  sort_field: date
  sort_reverse: true
autopages:
  enabled: true
  tags:
    title: Tag
    permalink: "/tag/:tag"
    layouts:
    - autopage_tags.html
    enabled: true
  categories:
    title: Kategori
    permalink: "/category/:cat"
    layouts:
    - autopage_cat.html
    enabled: true
  collections:
    enabled: false
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
adsense: disabled
adsense-data-ad-client: ca-pub-3412143450191416
adsense-data-ad-slot: '1363087678'
lazyimages: enabled
authorbox: disabled
sass:
  sass_dir: _sass
  style: compressed
exclude:
- changelog.md
- LICENSE.txt
- README.md
- Gemfile
- Gemfile.lock
algolia:
  application_id: E0LFP6WLUR
  index_name: disekitargame.com
  search_only_api_key: f8ee8c243a1ff62b972716eeb16494ac
